name = "BasicCraft"
author = "MisileLaboratory"
version = "1.28.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae4191f0139f48bf5074d7e8e594108a51bc15253498e5a448fdb012b3e60576"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
