name = "BasicCraft"
author = "MisileLaboratory"
version = "1.28.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63fcfd66c0b3cec7ef7abdf36b372af77f501e2d78e98c6031d282637d348eb8"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
