name = "BasicCraft"
author = "MisileLaboratory"
version = "1.30.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22c145d13ee7c7769b27ae1d889c797baaef61a3c940ce7b8b00f943e1c35a36"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
