name = "BasicCraft"
author = "MisileLaboratory"
version = "1.29.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aab2efd9bc24316c7120eddad9e4513cd5ad98b2246384e55f26ed8453aa66fd"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
