name = "BasicCraft"
author = "MisileLaboratory"
version = "1.21.0.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7e86f3e1cac30d65cdbd649ac05b2deb0ab93ee783d214d9eaba00605703650"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
