name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.8+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d5a8fa5d72ff2b81734f71fa0d28e1746fb6eedc8af6b06a073ee6946ae101e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
