name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.3+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7788ea9fe75b0cc22f78289ac83a76b0bbc72c856487f366d28f8a1485a9e624"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
