name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.8+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eff08b8c3768660c9618d3a0a38d70e78813f4d6191ef6719330918b5db476c5"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
