name = "BasicCraft"
author = "MisileLaboratory"
version = "1.19.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "246f87ea40c4ac1db1be679bee69abfb6739dc7149e60830afef2b8bd4dc264e"

[versions]
fabric = "0.14.22"
minecraft = "1.19.4"
