name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.4+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "128a79e7892c1639262203b32a63367c42a3c1a86eaebf1bdd69ddbc99dc85e7"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
