name = "BasicCraft"
author = "MisileLaboratory"
version = "1.17.6.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02bbbdd59ea72cd277656dfb17effc936c6119462105f88196c2e0c5d07db95e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
