name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.9+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b6d837c983eeca2122abcc1440e965fac868b4aa4a9270b0e97d61c3c464028"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
