name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.3+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "449f2ffd81193b8418cba8bb3826e8cc5735b0d30968bf9758aa3dbdf174683d"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
