name = "BasicCraft"
author = "MisileLaboratory"
version = "1.23.0.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b0b800c7e36eda10554706973788f643cf988d82de396a44a59626c62acc2d3"

[versions]
fabric = "0.15.3"
minecraft = "1.19.4"
