name = "BasicCraft"
author = "MisileLaboratory"
version = "1.16.0.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b08754dfc210cfb331b08505424223eded73c5dc37c528d388f6953dabc3784"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
