name = "BasicCraft"
author = "MisileLaboratory"
version = "1.23.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b85936e1c0cde85eef4a8bf71d11b386702465938cc3203cef7bdf1913002d1c"

[versions]
fabric = "0.15.3"
minecraft = "1.19.4"
