name = "BasicCraft"
author = "MisileLaboratory"
version = "1.17.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e465465023d6336b9aa33e1409fbd4e53aeed0f796de84e15599f7a9f80ba7"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
