name = "BasicCraft"
author = "MisileLaboratory"
version = "1.23.0+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bcaad36ac70085d1cdfaac4a62cb03588d9edcf2da74c84e38344f39deb8afe"

[versions]
fabric = "0.15.3"
minecraft = "1.19.4"
