name = "BasicCraft"
author = "MisileLaboratory"
version = "1.17.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1e1d07f1d5f5bb0c841df18a73a09091f6f8371747a6b17dbf07bdaef5282b5"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
