name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.2.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43f60d7ecc33a439fb29347f27dbe3c166a39bcffc786b1c9df4286193ff67d0"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
