name = "BasicCraft"
author = "MisileLaboratory"
version = "1.17.6+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "becfedffbbbc8bc3086670e720611ead09d21e04100943eef12364d83e2c1f4c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
