name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.2-alpha2+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ad3417611baf2ba1300af1bc716ba8e8086450bdb3e00a50a12b4f63db35f1"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
