name = "BasicCraft"
author = "MisileLaboratory"
version = "1.22.0.1+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab64e725f7bcc863a08c97c0c73fa8ecd7d76a00439ab3d2ffd614e746300378"

[versions]
fabric = "0.15.0"
minecraft = "1.19.4"
