name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.3+1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41fd747b8fcca06f5912ad118d9a7ccf138ec6bf24888461c8c4753ffb4bed22"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
