name = "Additive"
author = "SkywardMC"
version = "1.27.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a39d57d09c0dbed85493461bdf05c8dc926180967fe284e4ce06bad36d361c3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
