name = "BasicCraft"
author = "MisileLaboratory"
version = "1.29.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "812478bef0f6c9ca6e9bea5dfd613aab4323668968fdf934e8d20f817d9b3501"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
