name = "Additive"
author = "SkywardMC"
version = "1.26.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4bb34eb7d8db9253d34335c7488a10a033ebd68b3e4d70bf1574ed4014dafc5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
