name = "BasicCraft"
author = "MisileLaboratory"
version = "1.28.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed12a86d97fe935e1fedb979cbf48de72f3f5844705e2754db6025aa17b1ed8d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
