name = "BasicCraft"
author = "MisileLaboratory"
version = "1.29.1+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1501cec64f7b2e0205b0f7ff6b5c9224c1b11df0e358594279ddceb16f971495"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
