name = "BasicCraft"
author = "MisileLaboratory"
version = "1.30.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cae72c6c3a0aa8e7a2e956116d1108179c61305e3aeebe29563e751f1fdb0c4e"

[versions]
fabric = "0.16.5"
minecraft = "1.20.6"
