name = "BasicCraft"
author = "MisileLaboratory"
version = "1.28.0+1.20.6.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ad2c454964dd8a6c27674e8b75af009377226cbc6b115975ed9d79212d7082e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
