name = "BasicCraft"
author = "MisileLaboratory"
version = "1.44.0+26.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8aa7a7aef84714cb3d1ee76f5bd1394b9c7e34265d2bb6c74e05e8e66fa6edd"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-snapshot-1", "26.1-snapshot-2", "26.1-snapshot-3", "26.1-snapshot-4", "26.1-snapshot-5", "26.1-snapshot-6", "26.1-snapshot-7", "26.1-snapshot-8", "26.1-snapshot-9", "26.1-snapshot-10", "26.1-snapshot-11", "26.1-pre-1", "26.1-pre-2", "26.1-pre-3", "26.1-rc-1", "26.1-rc-2", "26.1-rc-3", "26.1"]
