name = "BasicCraft"
author = "MisileLab"
version = "26.4.2+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f17e358c6207cfb105d055a443adc63746465d3e0f5ae7d2d402985a921ff241"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
