name = "BasicCraft"
author = "MisileLab"
version = "26.4.2+mc26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2705e5008ec08b107730bc543863848393e92e42822e338c209bcab69299521b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
