name = "Additive"
author = "SkywardMC"
version = "1.31.0+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c85a5db7a35f8ee107d9ed6f942a957233dbaf9fa35824a7d343db78773c76de"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"
