name = "BasicCraft"
author = "MisileLab"
version = "26.2.0+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5358bc0e1e05a8069ef8b462a57e11c320ec3abe66ac9ca2eecd9055620955bf"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
