name = "Additive"
author = "SkywardMC"
version = "26.1.4+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a9cd9b677e54c109a7cf42ba71068f56fc8d9bbb2c200fc6547738f20d9e684"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
