name = "BasicCraft"
author = "MisileLab"
version = "26.2.0+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a3f5c08fb99140e569fbdcfbefa5461ff53ba1c85f3b91b44d96ace380a3f1"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
