name = "BasicCraft"
author = "MisileLab"
version = "26.3.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c783b375e896875bfb8c3698228dd08d59dad33cbb9c411d33c92bb9026e25b1"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
