name = "BasicCraft"
author = "MisileLab"
version = "26.2.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1eb56361b8fd719d6451c074890158c3d00bba32501b63e60c356eee56f3d1f"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
