name = "BasicCraft"
author = "MisileLab"
version = "26.2.1+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec5430f579c7f6003ff6eedd431d28dfa8c16975ff721a3179d41756b8cce3cb"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
