name = "BasicCraft"
author = "MisileLab"
version = "26.3.0+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9651a6a418113133fd5c946d7c9fdc1ec02aaf1d1a29bd3dc08e9b66dd706b77"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
