name = "BasicCraft"
author = "MisileLaboratory"
version = "1.23.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76268e4cbe6c2aca5ab57617a0dd97bef2cf8e3e0774289f7a76400938fb3c5e"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
