name = "BasicCraft"
author = "MisileLaboratory"
version = "1.24.4+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d90031c39ab72b4a9865f19c044825ebe004f6afcc9fb77dcb014291183a4b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
