name = "BasicCraft"
author = "MisileLaboratory"
version = "1.29.1+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c06e8d98dd41d0c97b0d44f009b571a773dff77bf2c8af1959bcfede2972750"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
