name = "BasicCraft"
author = "MisileLaboratory"
version = "1.28.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a4c864fec7c411e74fb875cbd3f5a9a84d2072864f1f5ad6dc9fcc387f36b3c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
