name = "BasicCraft"
author = "MisileLaboratory"
version = "1.30.0+1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d907340c27c002e61ea72f3e0ee2ad625b072c9516c2b5b09b6af21099ed04cb"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
