name = "BasicCraft"
author = "MisileLaboratory"
version = "1.23.0+1.20.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "260a9377a3a9bbd25d79b41e1e96e39a23a39d30b522b3a0cafe6da05ec47eac"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
