name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42f7b76f7d1579efef9bc2b1d02e9caf02d99f065c8440fe3d0d5fcab45dd0c6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
