name = "Additive"
author = "SkywardMC"
version = "1.37.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89bd2e2e4fddff7b64f372c737019ffcc524701c6a4fffd8796e72fb04f77eba"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
