name = "BasicCraft"
author = "MisileLaboratory"
version = "1.37.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b9f89770d415da65d257eec37aaff2df39c04e3e8fbacc4ecdda9e40697040f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
