name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "869585cf670bfade612a93b6873154e41a4cc3ac43a70401e19a155321a8fbf0"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
