name = "BasicCraft"
author = "MisileLaboratory"
version = "1.23.0.1+1.20.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29d670a7820a020532de49155a2c55cdab765ffb8f96172189f3a5d780b887f2"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
