name = "Additive"
author = "UltraStorm"
version = "1.13.2+1.19.2.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "810530a5ec0286e62741a11cc3ca4d8a4138b9cc9c6f58c9885f600a2a616433"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
