name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9133db95573a66e6105b43b1a60b4942dfbf85fee1469e9db950701cbb0804af"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
