name = "Additive"
author = "SkywardMC"
version = "1.32.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d49962337479673f3fefbfe809dd2f772464794b98cf7bd296534614d6a46913"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
