version = "1.33.0+1.21.4.fabric"
=======
name = "Additive"
author = "SkywardMC"
version = "1.33.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8e8759efc062151de4adcd49ce1c389adfea2a2cf0914dfc937dbc0604a9758"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
