name = "BasicCraft"
author = "MisileLaboratory"
version = "1.38.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2950c1f0922a515a399d56af111c97387b877fe812f12bcb545c8eddad93962b"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"
