name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "853a0f6eadf420e6e2ed14615f3938ad94e2099c4d10ccd8352ca1ce7bff7de6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
