name = "Additive"
author = "SkywardMC"
version = "1.38.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "447da85a078bce944d2cd5070cb81c2fcad7987495da171949410dfbed114fb0"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"
