name = "BasicCraft"
author = "MisileLaboratory"
version = "1.37.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f133c971c4cee3d0fd941fd1061d8bf90a63cc21d48e13b0b257f29f17c36c4e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
