name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2707824390ce6186c4e5c516d1bd92926218d00a04becc3ad28bf25313efc24a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
