name = "BasicCraft"
author = "MisileLaboratory"
version = "1.37.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1372473d7334bd680c0425fb42875603fc7edfc359701b93e921c84394f21024"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
