name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b6b66cd3ac54f2f66821fa5ebcf8dea592ec6b99966e5b9f3652d4da739e315"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
