name = "BasicCraft"
author = "MisileLab"
version = "26.1.4+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5762fa8ca79c78a20b0ecdef187e001c805df13ff896bc653a3dd1463275b48a"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
