name = "BasicCraft"
author = "MisileLab"
version = "26.3.0+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1b3ce6a6f569c5a457a9bc409fa3a8f0fff9a949019d9457317802798a1806b"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
