name = "Additive"
author = "SkywardMC"
version = "26.1.4+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "375caa5e188e06347874aad1cfa7b780a3d8c93fd1d1edb3abb6d7dfdde54f8e"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
