name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.7.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a1a292fa7adf8901a08943f845af44f6bba34abedc52e4c18bb7f0c6078e746"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"
