name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.7.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7db386a6ee10f904e9d25376f1f35379430b172c5969370ff6d66ec70c8cacd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"
