name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.7.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4c6ab1e91dbaacac65a98ad4eb4cf7cb539cc355389230149fd6d545386ae54"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"
