name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.2.1+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7bf5f3c014527cffb7586ce6a9b78d22fb341a100ad3254d53474712da14c08"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
