name = "BasicCraft"
author = "MisileLaboratory"
version = "1.14.0+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a737dd0474506f531fda46a776935e7e2bbe1286192364b0c0280b363f052b26"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
