name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.1.2+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ec37da2440b66414eb322bc1513bfc6545216ef1c5a3d562bbccde82b969c3c"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
