name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.0.1+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d67004dd1d591d79c9e7fd7a199a7a7556de03e2e58ae072d799612e80f21516"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
