name = "Additive"
author = "UltraStorm"
version = "1.13.2+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2914f32092417c4908469f15a90dc0980ad1d87ef54fc830097e63b763c0fc94"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
