name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.0.2+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a14bcdb3f94461a70e7713cb59e7a652e65665b08109aa7555bd3014e03a288"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
