name = "BasicCraft"
author = "MisileLaboratory"
version = "1.15.1.1+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ab1a401362075e87616f059794cf3b5bea543c86d232b67755bfd1b22fee17f"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
