name = "BasicCraft"
author = "MisileLaboratory"
version = "1.13.2.1+1.19.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3213f05d7848d6f7a0bdb3b41e2b7fa5bba30ab8b3afae78bf59f25391a384a0"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
